### ISSUE TITLE
Can support automatic file recursive protection in the folder

### ISSUE THREAD

**Issue by jamestotti** [alanzchen/rm-protection#6]
Can support automatic file recursive protection in the folder？

For example: to protect the mysql directory folder, after entering the mysql directory can not delete the current directory of the file

**Comment by alanzchen** [comment]
Did you mean: if a parent directory is protected, all the files inside should also be recursively protected?

**Comment by apocelipes** [comment]
I think it might be similar to the "-r" parameter for some commands, such as ’cp‘ or 'mv'.

**Comment by alanzchen** [comment]
@apocelipes 

Recursively protect every file inside a directory? Personally I won't encourage this behaviour, since "protecting everything is protecting nothing".

Currently you can protect folder but it won't protect anything inside it. (That is, it only shields you from `rm -rf folder`, but not `rm -rf folder\*`).

If anything inside a folder is protected, it will prompt to ask.

**Comment by apocelipes** [comment]
Well,thank you for telling me that 'protecting everything is protecting nothing'.

**Comment by alanzchen** [comment]
Hi,

Under the branch `recursive-protection`, now you can protect directories using `protect -R dir`. This will add an additional flag `R` in the third line of a protection file so it now looks like:
```
Question
Answer
R
```

For each argument that `rm-p` receives, `rm-p` will check if any of its parent directories is protected **and** has a flag `R` in the protection file. If so, `rm-p` will prompt.

Feel free to try it out and I will publish it on PyPi when it is well tested.

Thanks!

**Comment by alanzchen** [comment]
#7 should resolve this issue.
